#!/bin/bash
echo "travis debug"
docker login -u "$DOCKER_USERNAME" --p "$DOCKER_PASSWORD"
docker tag edxops/asym-crypto-yaml:latest edxops/asym-crypto-yaml:$TRAVIS_TAG
docker push edxops/asym-crypto-yaml:$TRAVIS_TAG
docker push edxops/asym-crypto-yaml:latest