#!/bin/bash
echo "I am in the script!"
docker login -u "$DOCKER_U" -p "$DOCKER_P"
docker tag edxops/asym-crypto-yaml:latest edxops/asym-crypto-yaml:$TRAVIS_TAG
docker push edxops/asym-crypto-yaml:$TRAVIS_TAG
docker push edxops/asym-crypto-yaml:latest